### ISSUE TITLE
issues with time counters

### ISSUE THREAD

**Issue by gnoff** [jeremyscalpello/node-2fa#1]
I think the 2 minute window might not be implemented as (I) expected.

per https://github.com/guyht/notp#opt-1

the window of 2 means the two previous and the 2 next tokens can all be valid at a given time (deltas ranging from -2 to 2 I presume) but since the time is set to 30 seconds this means that we have in practice at most a 1 minute window to verify the token. I the most you can guarantee (assuming fairly synchronized clocks) is a 60 second period where the otp is good.

Does that match your finding? Interested in bumping `window` to 4?

**Comment by jeremyscalpello** [comment]
So sorry for the late reply, didn't get an email notification for some reason.

I've reviewed the docs and you're right. The window has been increased to 4. :)
