### ISSUE TITLE
Add option to add my site image

### ISSUE THREAD

**Issue by Moebytes** [jeremyscalpello/node-2fa#31]
In Authy you can set a custom image and color, for example this is what the 2fa for Twitter looks like:

<img width="414" alt="twitterimg" src="https://user-images.githubusercontent.com/37512637/163897436-7df11eac-0096-4a48-a5ff-8ea0b95e602d.png">

Can you add this please?

**Comment by megadrive** [comment]
Those are Authy specific and not related to any library.

See: https://support.authy.com/hc/en-us/articles/360002908333-Adding-custom-logos-in-the-Authy-app

> As the vendor of an application, how can I change the logo associated with my application’s account token?
> There are two different scenarios with different solutions. If you are using the Authy API to generate your Authy account token, then you can change the logo in [Twilio Console](https://www.twilio.com/console). If you are not using the Authy API, then the Authy app uses Google Image Search API to find a logo, using your Google Authenticator token’s Issuer name as the default search term. The user can also try other search terms to find a better logo. The search results may not be perfect 100% of the time, because Google Image Search isn’t perfect. If you recently changed your application’s logo, it may take some time for Google to figure out that that is the most relevant logo for your application’s name. In general, we will not change your application’s logo to something different than what is returned by Google.
